name: SonarCloud Action

on:
  push:
    branches: [ "main", "stag", "dev" ]
  pull_request:
    branches: [ "main", "stag", "dev" ]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'bitnami/postgresql:14.8.0'
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: iquote_fastapi
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0'  # Adjust to your desired Go version

      - name: Install dependencies
        run: make deps

      - name: Test with Go Test
        run: make test
        
      - name: Test with Go Test with Coverage
        run: make test-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: nunenuh-github
